Repository zio/zio-macros, pull requests merged in 2019-10, with the labels that each got.

#7 Configure release
  .circleci/config.yml
  README.md
  build.sbt
  project/BuildHelper.scala
  project/SonatypeReleaseEarly.scala
  project/plugins.sbt
Labels: ci

#8 Code style & pre-release refactor
  .circleci/config.yml
  access-examples/shared/src/main/scala/zio/macros/access/Example.scala
  access/shared/src/main/scala/zio/macros/access/Accessable.scala
  build.sbt
  core/shared/src/main/scala/zio/macros/core/ModulePattern.scala
  mock/shared/src/main/scala/zio/macros/mock/Mockable.scala
  project/BuildHelper.scala
Labels: bug

#10 Update README.md
  README.md
Labels: documentation

#11 Publish zio-macros-core
  build.sbt
Labels: bug, ci

#13 import zio-delegate
  README.md
  access-examples/shared/src/main/scala/zio/macros/access/Example.scala
  access/shared/src/main/scala/zio/macros/access/Accessable.scala
  build.sbt
  core/shared/src/main/scala/zio/macros/core/ModulePattern.scala
  delegate-examples/shared/src/main/scala/zio/macros/delegate/Sys.scala
  delegate-tests/shared/src/test/scala/zio/macros/delegate/DelegateSpec.scala
  delegate-tests/shared/src/test/scala/zio/macros/delegate/MixSpec.scala
  delegate-tests/shared/src/test/scala/zio/macros/delegate/UnitSpec.scala
  delegate/shared/src/main/scala/zio/macros/delegate/Macros.scala
  delegate/shared/src/main/scala/zio/macros/delegate/Mix.scala
  delegate/shared/src/main/scala/zio/macros/delegate/annotations.scala
  docs/accessable.md
  docs/delegate.md
  docs/mix.md
  docs/mockable.md
  mock-examples/shared/src/main/scala/zio/macros/mock/Example.scala
  mock/shared/src/main/scala/zio/macros/mock/Mockable.scala
  project/BuildHelper.scala
Labels: enhancement

#15 Fix release
  build.sbt
  project/BuildHelper.scala
Labels: bug, ci

#29 Adjust mockable to mock improvements
  docs/mockable.md
  mock-examples/shared/src/main/scala/zio/macros/mock/Example.scala
  mock/shared/src/main/scala/zio/macros/mock/Mockable.scala
Labels: enhancement

#32 Accessible env type
  core/shared/src/main/scala/zio/macros/access/Accessible.scala
Labels: bug

#33 Handle non-abstract methods
  core-examples/shared/src/main/scala/zio/macros/access/Example.scala
  core/shared/src/main/scala/zio/macros/access/Accessible.scala
  core/shared/src/main/scala/zio/macros/core/ModulePattern.scala
  test-examples/shared/src/main/scala/zio/macros/mock/Example.scala
  test/shared/src/main/scala/zio/macros/mock/Mockable.scala
Labels: bug

#36 Handle URIO/RIO aliases
  core-examples/shared/src/main/scala/zio/macros/access/Example.scala
  core/shared/src/main/scala/zio/macros/core/ModulePattern.scala
  core/shared/src/main/scala/zio/macros/core/ZIOExtractor.scala
  test-examples/shared/src/main/scala/zio/macros/mock/Example.scala
Labels: bug
